model_params:
  in_channels: 3
  latent_dim: 256
  nfe: 64
  nfd: 64

exp_params:
  dataset: "training"
  data: "../../../data/sewer/paper/"
  image_size: 128
  batch_size: 128 # Better to have a square number
  LR: 0.0001
  weight_decay: 0.0
  scheduler_gamma: 0.95
  beta1: 0.9
  beta2: 0.999

trainer_params:
  gpus: 1
  max_epochs: 100
  n_workers: 16

logging_params:
  save_dir: "logs/"
  name: "VanillaAE"
  manual_seed: 1265
